# Generated by Django 4.1.7 on 2023-04-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedview",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, verbose_name="Allowed view slug"
            ),
        ),
    ]
