# Generated by Django 4.1.7 on 2023-04-28 22:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_allowedview_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="User Profile Pic"
            ),
        ),
    ]
