# Generated by Django 4.1.7 on 2023-07-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_resources_management", "0002_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date_issued",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date issued"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="invoice_description",
            field=models.TextField(verbose_name="Invoice description"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="paid_to",
            field=models.CharField(max_length=255, verbose_name="Paid to"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="price",
            field=models.FloatField(verbose_name="Amount due"),
        ),
    ]
