# Generated by Django 4.1.7 on 2023-03-20 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "milestone_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("delivery_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_name",
                    models.CharField(max_length=255, verbose_name="Update Name"),
                ),
                ("release_date", models.DateField(verbose_name="Release Date")),
                ("major_update", models.BooleanField(verbose_name="Major Update")),
                (
                    "release_description",
                    models.TextField(verbose_name="Release Description"),
                ),
            ],
            options={
                "verbose_name": "Scheduled Update",
                "verbose_name_plural": "Scheduled Updates",
            },
        ),
        migrations.CreateModel(
            name="ClientProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Project_Name", models.CharField(max_length=100)),
                ("Project_Description", models.CharField(max_length=900)),
                ("Category", models.CharField(max_length=100)),
                ("inprogress", models.BooleanField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients_management.client",
                    ),
                ),
            ],
        ),
    ]
