# Generated by Django 4.1.7 on 2023-04-25 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients_management", "0002_client_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
    ]
