# Generated by Django 4.1.7 on 2023-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients_management", "0003_alter_client_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientproject",
            name="Category",
        ),
        migrations.RemoveField(
            model_name="clientproject",
            name="Project_Description",
        ),
        migrations.RemoveField(
            model_name="clientproject",
            name="Project_Name",
        ),
        migrations.RemoveField(
            model_name="clientproject",
            name="inprogress",
        ),
        migrations.AddField(
            model_name="clientproject",
            name="proceeded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientproject",
            name="project_description",
            field=models.TextField(
                default="Project description", verbose_name="Project description"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientproject",
            name="project_name",
            field=models.CharField(
                default="project name", max_length=100, verbose_name="Project name"
            ),
            preserve_default=False,
        ),
    ]
