# Generated by Django 4.1.7 on 2023-04-25 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("staff_performance_tracking", "0003_staffmember_skills"),
        ("clients_management", "0004_remove_clientproject_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientproject",
            options={
                "verbose_name": "Client project",
                "verbose_name_plural": "Client projects",
            },
        ),
        migrations.AddField(
            model_name="clientproject",
            name="staff_members",
            field=models.ManyToManyField(
                related_name="staff_members",
                to="staff_performance_tracking.staffmember",
                verbose_name="Staff members",
            ),
        ),
        migrations.AddField(
            model_name="clientproject",
            name="started_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Started at",
            ),
            preserve_default=False,
        ),
    ]
