# Generated by Django 4.1.7 on 2023-04-25 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients_management", "0005_alter_clientproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientproject",
            name="supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supervisor",
            ),
        ),
    ]
