# Generated by Django 4.1.7 on 2023-07-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients_management", "0007_alter_clientprojectmilestone_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Client meeting description"),
                ),
                (
                    "client_satisfaction",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="Client satisfaction",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients_management.client",
                        verbose_name="Related client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client meeting",
                "verbose_name_plural": "Client meetings",
            },
        ),
    ]
