# Generated by Django 4.1.7 on 2023-07-05 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients_management", "0009_clientmeeting_client_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientmeeting",
            name="client_satisfaction",
        ),
    ]
