# Generated by Django 4.1.7 on 2023-07-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients_management", "0011_remove_clientmeeting_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledupdate",
            name="is_released",
            field=models.BooleanField(default=False, verbose_name="Is released"),
        ),
    ]
