# Generated by Django 4.1.7 on 2023-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_performance_tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=350, verbose_name="Skill name")),
                (
                    "slug",
                    models.SlugField(blank=True, null=True, verbose_name="Skill slug"),
                ),
            ],
            options={
                "verbose_name": "Staff skill",
                "verbose_name_plural": "Staff skills",
            },
        ),
    ]
