# Generated by Django 4.1.7 on 2023-04-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_performance_tracking", "0002_staffskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="skills",
            field=models.ManyToManyField(
                related_name="staff_skills",
                to="staff_performance_tracking.staffskill",
                verbose_name="Skills",
            ),
        ),
    ]
