# Generated by Django 4.1.7 on 2023-04-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients_management", "0006_clientproject_supervisor"),
        (
            "staff_performance_tracking",
            "0004_alter_task_options_remove_task_delivery_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="client_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients_management.clientproject",
                verbose_name="Related client project",
            ),
        ),
    ]
