# Generated by Django 4.1.7 on 2023-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_performance_tracking", "0009_task_is_proceeded"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                default="In progress", max_length=350, verbose_name="Status"
            ),
            preserve_default=False,
        ),
    ]
