# Generated by Django 4.1.7 on 2023-07-05 13:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff_performance_tracking", "0010_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_submission",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
    ]
