# Generated by Django 4.1.7 on 2023-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_performance_tracking", "0012_alter_task_task_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_submission",
            field=models.URLField(
                blank=True,
                max_length=350,
                null=True,
                verbose_name="Task submission url",
            ),
        ),
    ]
